[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

# Other settings...

[server]
enableCORS = false
port = 8501

# Hide the GitHub icon
[ui]
hideSidebarNav = false
hideFooter = false
hideGitHubButton = true